FROM mysql:8.0

# Set correct enviorment (Also possible with docker run -e)
ENV MYSQL_ROOT_PASSWORD=mysecretpassword
ENV MYSQL_DATABASE=taskiteasy
ENV MYSQL_USER=taskiteasy
ENV MYSQL_PASSWORD=taskiteasy

EXPOSE 3306
